spring:
  application:
    name: recetas-api

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://admin:admin@clusterrecetas.c1zs8sz.mongodb.net/recetas_db?retryWrites=true&w=majority&appName=ClusterRecetas}

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.data.mongodb.core: ${LOG_LEVEL:INFO}

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    org.springframework.data.mongodb.core: INFO
